services:
  avaliacao:
    container_name: avaliacao
    image: app/avaliacao:latest
    build: .
    depends_on:
      - postgresdb
      - minio
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Cuiaba"
      SERVER_PORT: 8080
      SPRING_DATASOURCE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/avaliacao-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVERCLASS: org.postgresql.Driver

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avaliacao-db
    ports:
       - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin:/var/lib/pgadmin/

  minio:
    image: minio/minio:latest
    volumes:
      - 'minio_data:/data'
    environment:
      TZ: "America/Cuiaba"
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ACCESS_KEY: "root"
      MINIO_SECRET_KEY: "password"
      MINIO_DEFAULT_BUCKETS: "spavaliacao-bucket"
    command: server /data  --console-address ":9001"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres_data:
  pgadmin:
  minio_data:
    driver: local