spring:
  application:
    name: avaliacao
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
    #  hibernate:
    #    jdbc.lob.non_contextual_creation: true
    #    generate_statistics: false
    #    id.optimizer.pooled.preferred: pooled-lo
    #    jdbc.batch_size: 10
    #    order_inserts: true
    #    order_updates: true
    #    batch_versioned_data: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #database: POSTGRESQL
  datasource:
    #initialization-mode: always
    #platform: postgres
    url: jdbc:postgresql://localhost:5432/avaliacao-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: collection-pool
  flyway:
    enabled: false

springdoc:
  api-docs:
    path: /api-docs

server:
  servlet:
    context-path: "/api"