## spring config ##
spring:
  application:
    name: avaliacao
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
        dialect: ${SPRING_DATASOURCE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/avaliacao-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: ${SPRING_DATASOURCE_DRIVERCLASS:org.postgresql.Driver}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: collection-pool
  flyway:
    enabled: false
  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 1000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


springdoc:
  api-docs:
    path: /api-docs

## server config ##
server:
  servlet:
    context-path: "/api"
  error:
    include-message: always
    include-stacktrace: never
  port: ${SERVER_PORT:8080}

## minio
minio:
  url: http://127.0.0.1:9000
  access-key: root
  secret-key: password
  bucket-name: spavaliacao-bucket

#### app config ####
app:
  application-description: '@project.description@'
  application-version: '@project.version@'